train_file_num: 0
population_size: 500
n_generations: 250
n_elitism: 10
crossover_rate: 0.7
mutation_loops: 4
inter_swap_mutation_rate: 0.3
cross_swap_mutation_rate: 0.5
inter_insert_mutation_rate: 0.2
cross_insert_mutation_rate: 0.4
scramble_mutation_rate: 0.03
scramble_len: 4
inversion_mutation_rate: 0.06
inversion_len: 4
initial_pop_function: StartTime
fitness_punishment_factor: 1.5