train_file_num: 9
population_size: 5000
n_generations: 400000
n_elitism: 1
n_stagnations: 30000
crossover_rate: 0.9
mutation_loops: 4
inter_swap_mutation_rate: 0.01
cross_swap_mutation_rate: 0.03
inter_insert_mutation_rate: 0.01
cross_insert_mutation_rate: 0.03
scramble_mutation_rate: 0.001
scramble_len: 4
inversion_mutation_rate: 0.003
inversion_len: 4
initial_pop_function: StartTime
fitness_punishment_factor: 0.5