train_file_num: 9
population_size: 100
n_generations: 40000
n_elitism: 1
n_stagnations: 30000
crossover_rate: 0.7
mutation_loops: 2
heuristic_cluster_mutation_rate: 0.3
initial_pop_function: StartTime
fitness_punishment_factor: 0.5