# File
train_file_num: 9

# Hyperparameters
population_size: 150
n_generations: 10000000
n_elitism: 1
n_stagnations: 3000
crossover_rate: 0.9
fitness_punishment_factor: 2.0

# Mutation
mutation_loops: 3
heuristic_cluster_mutation_rate: 0.08
random_swap_mutation_rate: 0.05
heuristic_swap_mutation_rate: 0.09
heuristic_random_swap_mutation_rate: 0.08
large_neighbourhood_mutation_rate: 0.05

# Parent Selection
n_parents_scaling: 2.0

# Linear Ranking
s: 1.5

# Crowding
# 0 for deterministic, 1 for probabilistic
scaling_factor: 1.1

# Functions
init_population_fn: File #Feasible, File
parent_selection_fn: LinearRanking
crossover_fn: Visma
survivor_selection_fn: CrowdingOptimized
