# File
file_name: train_9

# Initial printing and graph
print_and_graph: true

# Hyperparameters
population_size: 200
n_generations: 300000000
n_elitism: 1
n_stagnations: 9000
crossover_rate: 0.3
fitness_punishment_factor: 4.5
tournament_size: 3

use_islands: true

# Mutation
heuristic_cluster_mutation_rate: 0.1
heuristic_swap_mutation_rate: 0.2
heuristic_random_swap_mutation_rate: 0.2
insert_mutation_rate: 0.2
large_neighbourhood_mutation_rate: 0.03

# Parent Selection
n_parents_scaling: 3.0

# Linear Ranking (between 1-2)
s: 1.8

# Crowding
# 0 for deterministic, 1 for probabilistic
scaling_factor: 0.9

# Functions
#Feasible, File
init_population_fn: Feasible

parent_selection_fn: LinearRanking

# Visma, VismaOptimized, VismaIndexed
crossover_fn: VismaOptimized

# CrowdingOptimized, Crowding, Tournament
survivor_selection_fn: CrowdingOptimized

# Keep, Delete
scramble_fn: Delete