# File
train_file_num: 9

# Hyperparameters
population_size: 100
n_generations: 100000
n_elitism: 1
n_stagnations: 3000
crossover_rate: 0.85
fitness_punishment_factor: 3.3

# Mutation
mutation_loops: 1
heuristic_cluster_mutation_rate: 0.6
random_swap_mutation_rate: 0.1
heuristic_swap_mutation_rate: 0.3

# Parent Selection
n_parents_scaling: 3

# Linear Ranking
s: 1.2

# Crowding
# 0 for deterministic, 1 for probabilistic
scaling_factor: 1.

# Functions
init_population_fn: Feasible
parent_selection_fn: LinearRanking
crossover_fn: Visma
survivor_selection_fn: CrowdingOptimized
