train_file_num: 9
population_size: 350
n_generations: 40000
n_elitism: 5
n_stagnations: 30000
crossover_rate: 0.7
mutation_loops: 1
heuristic_cluster_mutation_rate: 0.3
init_population_fn: Feasible
parent_selection_fn: LinearRanking
fitness_punishment_factor: 3.5

# Linear Ranking
s: 1.3