# File
train_file_num: 9

# Hyperparameters
population_size: 150
n_generations: 100000
n_elitism: 1
n_stagnations: 600
crossover_rate: 0.8
fitness_punishment_factor: 1.6

# Mutation
mutation_loops: 1
heuristic_cluster_mutation_rate: 0.15
random_swap_mutation_rate: 0.05
heuristic_swap_mutation_rate: 0.09
heuristic_random_swap_mutation_rate: 0.08

# Parent Selection
n_parents_scaling: 3.2

# Linear Ranking
s: 1.5

# Crowding
# 0 for deterministic, 1 for probabilistic
scaling_factor: 1.1

# Functions
init_population_fn: Feasible
parent_selection_fn: LinearRanking
crossover_fn: Visma
survivor_selection_fn: CrowdingOptimized
