# File
file_name: train_9

port: 8080

# Initial printing and graph
print_and_graph: true
log_frequency: 100

# Hyperparameters
population_size: 150
n_generations: 300000000
n_elitism: 1
n_stagnations: 500
crossover_rate: 0.5
fitness_punishment_factor: 4.5
tournament_size: 3

# Max run time in seconds. -1 for no constraint
run_time: 180

# ---------- islands ----------
use_islands: true
island_share_frequency: 600

# Mutation
heuristic_cluster_mutation_rate: 0.2
heuristic_swap_mutation_rate: 0.2
heuristic_random_swap_mutation_rate: 0.001 # Bad to have high
insert_mutation_rate: 0.001 # Bad to have high
large_neighbourhood_mutation_rate: 0.001 # Bad to have high

# Parent Selection
n_parents_scaling: 3.0

# Linear Ranking (between 1-2). Higher means more probability of choosing the best individual
s: 1.8

# Crowding
# 0 for deterministic, 1 for probabilistic
scaling_factor: 0.9


# ------- Functions -------
# Feasible, File
init_population_fn: Feasible

# LinearRanking, Tournament, Probabilistic
parent_selection_fn: LinearRanking

# Visma, VismaIndexed, VismaMoreOptimized
# Don't use Visma Indexed. It is bad. See report
crossover_fn: Visma
crossover_tries: 3

# Crowding
survivor_selection_fn: Crowding

# Keep, Delete
scramble_fn: Delete